
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 26 20:19:02 CEST 2018
//----------------------------------------------------

package ba140645d.mjcompiler.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 19;
  public static final int CONST = 16;
  public static final int OP_LESSER_EQUAL = 31;
  public static final int OP_GREATER = 28;
  public static final int CONTINUE = 15;
  public static final int OP_L_SQUARED_PARENTHESES = 42;
  public static final int NUM_CONST = 18;
  public static final int OP_MULTIPLICATION = 23;
  public static final int OP_LOGIC_OR = 33;
  public static final int IDENTIFIKATOR = 17;
  public static final int OP_EQUALS = 26;
  public static final int OP_INCREMENT = 35;
  public static final int OP_SUBTRACTION = 22;
  public static final int OP_MODUO = 25;
  public static final int OP_DOT = 39;
  public static final int CLASS = 4;
  public static final int OP_ADDITION = 21;
  public static final int IF = 6;
  public static final int OP_R_BRACE_PARENTHESES = 45;
  public static final int OP_DECREMENT = 36;
  public static final int OP_R_SQUARED_PARENTHESES = 43;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int OP_L_PARENTHESES = 40;
  public static final int OP_DIVISION = 24;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int OP_LESSER = 30;
  public static final int OP_LOGIC_AND = 32;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int OP_GREATER_EQUAL = 29;
  public static final int ELSE = 5;
  public static final int OP_R_PARENTHESES = 41;
  public static final int OP_SEMICOLN = 37;
  public static final int READ = 9;
  public static final int OP_NOT_EQUALS = 27;
  public static final int WHILE = 13;
  public static final int OP_COMMA = 38;
  public static final int EXTENDS = 14;
  public static final int BOOL_CONST = 20;
  public static final int OP_EQUAL = 34;
  public static final int OP_L_BRACE_PARENTHESES = 44;
  public static final int PRINT = 8;
  public static final int DO = 12;
}

