
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Apr 26 17:43:04 CEST 2018
//----------------------------------------------------

package ba140645d.mjcompiler.parser;

/** CUP generated class containing symbol constants. */
public class Symbols {



    /*
    //**********************************************
    //********         KLJUCNE RECI      ***********
    //**********************************************
    public static final int PROGRAM     = 1;
    public static final int BREAK       = 2;
    public static final int CLASS       = 3;
    public static final int ELSE        = 4;
    public static final int IF          = 5;
    public static final int NEW         = 6;
    public static final int PRINT       = 7;
    public static final int READ        = 8;
    public static final int RETURN      = 9;
    public static final int VOID        = 10;
    public static final int DO          = 11;
    public static final int WHILE       = 12;
    public static final int EXTENDS     = 13;
    public static final int CONTINUE    = 14;




    // IDENTIFIKATOR
    public static final int IDENTIFIKATOR = 100;


    // KONSTANTE
    public static final int NUM_CONST   = 200;
    public static final int CHAR_CONST  = 201;
    public static final int BOOL_CONST  = 202;



    // OPERATORI
    public static final int OP_ADDITION                 = 300;
    public static final int OP_SUBTRACTION              = 301;
    public static final int OP_MULTIPLICATION           = 302;
    public static final int OP_DIVISION                 = 303;
    public static final int OP_MODUO                    = 304;
    public static final int OP_EQUALS                   = 305;
    public static final int OP_NOT_EQUALS               = 306;
    public static final int OP_GREATER                  = 307;
    public static final int OP_GREATER_EQUAL            = 308;
    public static final int OP_LESSER                   = 309;
    public static final int OP_LESSER_EQUAL             = 310;
    public static final int OP_LOGIC_AND                = 311;
    public static final int OP_LOGIC_OR                 = 312;
    public static final int OP_EQUAL                    = 313;
    public static final int OP_INCREMENT                = 314;
    public static final int OP_DECREMENT                = 315;
    public static final int OP_SEMICOLN                 = 316;
    public static final int OP_COMMA                    = 317;
    public static final int OP_L_PARENTHESES            = 318;
    public static final int OP_R_PARENTHESES            = 319;
    public static final int OP_L_SQUARED_PARENTHESES    = 320;
    public static final int OP_R_SQUARED_PARENTHESES    = 321;
    public static final int OP_L_BRACE_PARENTHESES      = 322;
    public static final int OP_R_BRACE_PARENTHESES      = 323;
    public static final int OP_DOT                      = 324;


    // EOF
    public static final int EOF = 999;
    */
}

